# Generated by Django 4.1.2 on 2024-03-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0026_alter_booklandrent_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('mob', models.IntegerField(null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('image', models.FileField(upload_to='')),
                ('address', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
