# Generated by Django 4.1.2 on 2024-03-05 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0027_user_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='loginid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
