# Generated by Django 4.1.2 on 2024-03-05 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0028_user_reg_loginid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('amount', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('fid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmerapp.farmer')),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmerapp.products')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmerapp.user_reg')),
            ],
        ),
    ]
