# Generated by Django 4.1.2 on 2024-04-06 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0029_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('img', models.FileField(null=True, upload_to='')),
                ('url', models.URLField(null=True)),
                ('desc', models.CharField(max_length=300, null=True)),
                ('ftid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmerapp.farmtech')),
            ],
        ),
    ]
